### ISSUE TITLE
Add a requestId or Token

### ISSUE THREAD

**Issue by denebchorny** [alhazmy13/Gota#2]
The idea is simple, allow placing a requestId or token to be receiven in onRequestBack".

What is this for? You may be wondering.

I just happened that I require use variables to make a difference in functionality when I am using buttons that have almost the same permissions in different situations.

For example, I have two buttons. One is to use the camera and another is to use the camera and contact list. For the first button I do not require permission contact but I require for the second one.

If there is the token or requestId I could do something like:

``` java
Activity{
...

Gota.Builder permitionCamera;
    Gota.Builder permitionCameraAndContacts;

@Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main2);

        permitionCamera = new Gota.Builder(this)
                .withPermissions(Manifest.permission.CAMERA)
                .requestId(0)                
                .setListener(this);

        permitionCameraAndContacts = new Gota.Builder(this)
                .withPermissions(Manifest.permission.CAMERA, Manifest.permission.READ_CONTACTS)
                 .requestId(1)
                .setListener(this);
    }



@Override
    public void onRequestBack(GotaResponse gotaResponse) {
        switch (gotaResponse.requestId) {
            case 0:
                if (gotaResponse.isGranted(Manifest.permission.CAMERA)) {
                    //Do what you want
                }
                break;

            case 1:
                if (gotaResponse.isAllGranted()) {
                    // do what you want
                }
                break;
        }
    }
...
}
```

I think it is easier to understand the code. I hope you understand me.

Thanks for everything.

**Comment by alhazmy13** [comment]
Done,,
It's supported with version 1.3.0

Thank You
