### ISSUE TITLE
Add more functions to GotaResponse

### ISSUE THREAD

**Issue by denebchorny** [alhazmy13/Gota#3]
Hi again Sir,

I have another idea. You can add others functions to GotaResponse class as "On Never Ask Again"
as this library do https://github.com/hotchemi/PermissionsDispatcher.

A function called "isOnNeverAskAgain(String)" to know if the permission was denied and selected as never ask again. This could let the developers to know how to act in this kind of situation.

Thanks in advace, Sir.

Have a nice day

**Comment by alhazmy13** [comment]
it's supported on version 1.3.0
Thank You
