### ISSUE TITLE
transition غريب عند استعمال المكتبة

### ISSUE THREAD

**Issue by AsimNet** [alhazmy13/Gota#4]
السلام عليكم..

أنا أستعمل المكتبة بالشكل التالي: 
```
  new Gota.Builder(this)
                .withPermissions(Manifest.permission.ACCESS_FINE_LOCATION)
                .requestId(1)
                .setListener(this)
                .check();
```

لاحظت وجود حركة بالاكتفتي غير مرغوب فيها، وعند ازالة هذا السطر تزول هذه الحركة
![ezgif com-gif-maker](https://cloud.githubusercontent.com/assets/3624441/25313460/ed8a54ea-2837-11e7-83c2-39662e07c911.gif)

**Comment by alhazmy13** [comment]
اهلا @AsimNet 

نعم المكتبة فعلياً تقوم بتشغيل اكتفتي للتحقق من الصلاحيات, ماهو الجهاز الذي تستخدمه؟ وكم رقم اصدار الاندرويد الموجود لديك؟

**Comment by AsimNet** [comment]
shiomi redmi 3s
Android 6.0
